CREATE DATABASE NETWORK_INVENTORY;
use NETWORK_INVENTORY;

CREATE TABLE DEVICE_TYPE (
DEV_MOD VARCHAR(30) primary key not null,
DEV_TYPE VARCHAR(30) NOT NULL,
DEV_OS_VERSION VARCHAR(30) NOT NULL,
DEV_PART_NO VARCHAR(30) NOT NULL
);

CREATE TABLE DEVICE (
DEV_MOD  VARCHAR(30) NOT NULL,
DEV_HOST_NAME  VARCHAR(30) NOT NULL,
DEV_LOCATION  VARCHAR(30) NULL,
DEV_IP  VARCHAR(16) NOT NULL,
DEV_SERIAL_NO  VARCHAR(30) NOT NULL,
DEV_ID  VARCHAR(50) PRIMARY KEY NOT NULL, /*(DEV_IP, DEV_HOST_NAME) */
foreign key (DEV_MOD) references DEVICE_TYPE(DEV_MOD)
);

CREATE TABLE MODULE_TYPE (
MODULE_MOD  VARCHAR(30)  primary key not null,
MODULE_TYPE  VARCHAR(15) NOT NULL,
MODULE_OS_VERSION  VARCHAR(30) NOT NULL,
MODULE_PART_NO  VARCHAR(30) NOT NULL
);

CREATE TABLE MODULE_DEVICE (
MODULE_MOD  VARCHAR(30)  not null,
DEV_ID  VARCHAR(50) primary key NOT NULL,
MODULE_SERIAL_NO VARCHAR(30)  not null,
foreign key (MODULE_MOD) references MODULE_TYPE(MODULE_MOD),
foreign key (DEV_ID) references DEVICE(DEV_ID)
);


CREATE TABLE DEVICE_INTERFACES (
INT_NAME  VARCHAR(30) NOT NULL,
INT_DESC  VARCHAR(30) NULL,
INT_TYPE  VARCHAR(30) NOT NULL,
INT_IP  VARCHAR(30) NOT NULL,
DEV_ID VARCHAR(50) NOT NULL,
INT_ID  VARCHAR(60) PRIMARY KEY  NOt NULL, -- (INT_IP, INT_NAME)
foreign key (DEV_ID) references MODULE_DEVICE(DEV_ID)
);
